Repository thousandbrainsproject/tbp.monty, pull requests merged in 2024-12, with the labels that each got.

#84 ci: grant pull-requests write to cla workflow
  .github/workflows/cla.yml
Labels: triaged

#89 docs: update broken link
  docs/contributing/request-for-comments-rfc.md
Labels: documentation, triaged

#93 Add bluesky to api docs
  tools/generate_api_docs/source/conf.py
Labels: documentation, triaged

#108 docs: add cla label to faciliate pull request triage
  docs/contributing/guides-for-maintainers/triage.md
Labels: documentation, triaged

#106 Update glossary.md
  docs/overview/glossary.md
Labels: documentation, triaged

#98 Update capabilities-of-the-system.md
  docs/overview/vision-of-the-thousand-brains-project/capabilities-of-the-system.md
Labels: documentation, triaged

#99 Update learning-modules.md
  docs/overview/architecture-overview/learning-modules.md
Labels: documentation, triaged

#103 Update application-criteria.md
  docs/overview/application-criteria.md
Labels: documentation, triaged

#105 Update results-from-alternative-implementations.md
  docs/overview/benchmark-experiments/results-from-alternative-implementations.md
Labels: documentation, triaged

#100 Update cortical-messaging-protocol.md
  docs/overview/architecture-overview/cortical-messaging-protocol.md
Labels: documentation, triaged

#101 Update other-aspects.md
  docs/overview/architecture-overview/other-aspects.md
Labels: documentation, triaged

#102 Update bringing-it-together.md
  docs/overview/architecture-overview/bringing-it-together.md
Labels: documentation, triaged

#104 Update benchmark-experiments.md
  docs/overview/benchmark-experiments.md
Labels: documentation, triaged

#111 Add missing links
  docs/hierarchy.md
Labels: documentation, triaged

#112 Fix links for slugs
  docs/future-work/cmp-hierarchy-improvements/add-top-down-connections.md
  docs/future-work/framework-improvements/add-infrastructure-for-multiple-agents-that-move-independently.md
  docs/future-work/learning-module-improvements.md
  docs/future-work/learning-module-improvements/contributing-learning-modules.md
  docs/future-work/learning-module-improvements/reinitialize-hypotheses-when-starting-to-recognize-a-new-object.md
  docs/future-work/learning-module-improvements/support-scale-invariance.md
  docs/future-work/learning-module-improvements/test-particle-filter-like-resampling-of-hypothesis-space.md
  docs/future-work/learning-module-improvements/use-better-priors-for-hypothesis-initialization.md
  docs/future-work/motor-system-improvements.md
  docs/future-work/motor-system-improvements/implement-a-simple-cross-modal-policy-for-sensory-guidance.md
  docs/future-work/motor-system-improvements/implement-switching-between-learning-and-inference-focused-policies.md
  docs/future-work/motor-system-improvements/interpret-goal-states-in-motor-system-switch-policies.md
  docs/future-work/motor-system-improvements/reuse-hypothesis-testing-policy-target-points.md
  docs/future-work/motor-system-improvements/top-down-exploration-policy.md
  docs/future-work/voting-improvements/outline-routing-protocol-attention.md
  docs/hierarchy.md
Labels: bug, documentation, triaged

#94 Utilities for generating `monty_config` and `dataset_args` for an arbitrary number of LMs.
  src/tbp/monty/frameworks/config_utils/config_args.py
  src/tbp/monty/frameworks/config_utils/make_dataset_configs.py
Labels: enhancement, triaged

#115 rfc: mermaid diagram trailing spaces required for preview to render
  rfcs/0004_action_object/habitatenv_step_seq_diagram_desired.md
Labels: triaged

#109 Fix division by zero when running the tutorial experiment
  src/tbp/monty/frameworks/models/motor_policies.py
Labels: triaged

#118 docs: update Anaconda env create commands for latest version
  docs/how-to-use-monty/getting-started.md
Labels: documentation, triaged

#120 Update Link to Roadmap Sheet
  docs/future-work/project-roadmap.md
Labels: documentation

#119 Add Citation for TBP Whitepaper
  README.md
  docs/overview/further-reading.md
  docs/overview/welcome-to-the-thousand-brains-project-documentation.md
Labels: documentation, triaged
