Repository thousandbrainsproject/tbp.monty, pull requests merged in 2024-11, with the labels that each got.

#49 A typo in tutorials.md
  docs/how-to-use-monty/tutorials.md
Labels: documentation, triaged

#50 Docs: fix broken social icons
  docs/overview/welcome-to-the-thousand-brains-project-documentation.md
Labels: documentation, triaged

#47 ci: grant cla-assistant ability to write comments on issues and PRs
  .github/workflows/cla.yml
Labels: infrastructure, triaged

#54 Docs: rename title to match slug after slug change
  docs/overview/application-criteria.md
Labels: documentation, triaged

#48 Fix first experiment run docs
  docs/how-to-use-monty/getting-started.md
  environment_arm64.yml
Labels: triaged

#57 docs: add instructions for downloading worldimages
  docs/overview/benchmark-experiments.md
Labels: documentation, triaged

#56 Docs: Welcome page resources in a table and added Bluesky reference
  docs/figures/overview/bluesky.png
  docs/overview/welcome-to-the-thousand-brains-project-documentation.md
Labels: documentation, triaged

#55 docs: conda init instructions
  docs/how-to-use-monty/getting-started.md
  environment.yml
  environment_arm64.yml
Labels: triaged

#53 Add vectorized figures
  docs/figures/how-monty-works/agent_vs_sensors_w_labels.png
  docs/figures/how-monty-works/evidence_init_all.png
  docs/figures/how-monty-works/evidence_update1.png
  docs/figures/how-monty-works/evidence_update2.png
  docs/figures/how-monty-works/example_movement.png
  docs/figures/how-monty-works/five_lm_monty.png
  docs/figures/how-monty-works/five_lm_views.jpg
  docs/figures/how-monty-works/five_lm_views.png
  docs/figures/how-monty-works/full_graph.png
  docs/figures/how-monty-works/learn_from_scratch.png
  docs/figures/how-monty-works/observations_w_labels.png
  docs/figures/how-monty-works/overview_diagram.png
  docs/figures/how-monty-works/policies.png
  docs/figures/how-monty-works/possible_matches.png
  docs/figures/how-monty-works/search_radius.png
  docs/figures/how-monty-works/step_episode_epoch.png
  docs/figures/how-monty-works/touch_vs_vision.png
  docs/figures/how-monty-works/voting.png
  docs/figures/overview/cc_voting.png
  docs/figures/overview/cortical_columns_lm.png
  docs/figures/overview/overview_diagram.png
  docs/figures/overview/reference_frames.png
  docs/figures/overview/s_mand_lm.png
  docs/figures/overview/scaling.png
  docs/figures/overview/sm_and_lm.png
  docs/how-monty-works/environment-agent.md
  docs/how-monty-works/how-learning-modules-work.md
  docs/how-monty-works/observations-transforms-sensor-modules.md
  docs/overview/architecture-overview/bringing-it-together.md
  docs/overview/architecture-overview/sensor-modules.md
Labels: documentation, triaged

#61 Actions: Link checker
  .github/workflows/docs.yml
  docs/overview/welcome-to-the-thousand-brains-project-documentation.md
Labels: infrastructure, triaged

#69 docs: GitHub Actions naming convention in style guide
  docs/contributing/style-guide.md
Labels: documentation, triaged

#72 ci: use commit sha instead of HEAD to check changes on push
  .github/actions/should_run_monty/action.yml
  .github/workflows/docs.yml
  .github/workflows/tools.yml
Labels: infrastructure, triaged

#73 ci: should_run_monty action explicit inputs
  .github/actions/should_run_monty/action.yml
  .github/workflows/monty.yml
  .github/workflows/monty_api_docs.yml
Labels: infrastructure, triaged

#74 ci: generate pages artifact in Monty API Docs workflow
  .github/workflows/monty.yml
  .github/workflows/monty_api_docs.yml
Labels: infrastructure, triaged

#75 ci: provide required github-token param
  .github/workflows/monty_api_docs.yml
Labels: infrastructure, triaged

#77 fix: export habitat actuator symbols that are used as types
  src/tbp/monty/simulators/habitat/actuator.py
Labels: triaged

#78 Docs: More Engaging Readme
  README.md
  docs/figures/overview/discourse_screenshot.png
  docs/figures/overview/docs_screenshot.png
  docs/figures/overview/youtube_screenshot.png
Labels: documentation, triaged

#80 Docs: Align images
  README.md
Labels: documentation, triaged

#76 Docs: Glossary Addition for Model
  docs/overview/glossary.md
Labels: documentation, triaged

#79 refactor: remove habitat_sim dependency in motor_policies.py
  src/tbp/monty/frameworks/models/motor_policies.py
Labels: triaged

#68 docs: avoid PRs based on unmerged PRs
  docs/contributing/guides-for-maintainers/triage.md
Labels: documentation, triaged
