Repository thousandbrainsproject/tbp.monty, pull requests merged in 2025-01, with the labels that each got.

#122 Updates for new Org
  README.md
  docs/community/code-of-conduct.md
  docs/community/our-licence-and-patent-pledge-explained.md
  docs/contributing/contributing.md
  docs/contributing/why-contribute.md
  docs/overview/faq-thousand-brains-project.md
  docs/overview/vision-of-the-thousand-brains-project/challenging-preconceptions.md
Labels: documentation, triaged

#64 Tools: Resize images in markdown
  docs/contributing/style-guide.md
  docs/figures/future-work/monty_tasks.png
  docs/how-monty-works/how-learning-modules-work.md
  docs/how-monty-works/policy.md
  docs/overview/architecture-overview/learning-modules.md
  docs/overview/architecture-overview/sensor-modules.md
  docs/overview/benchmark-experiments.md
  docs/overview/welcome-to-the-thousand-brains-project-documentation.md
  pyproject.toml
  tools/github_readme_sync/hierarchy.py
  tools/github_readme_sync/readme.py
  tools/github_readme_sync/tests/readme_test.py
Labels: infrastructure, triaged

#67 Tools: Make external-link checker faster
  README.md
  docs/contributing/contributing.md
  docs/overview/welcome-to-the-thousand-brains-project-documentation.md
  tools/github_readme_sync/colors.py
  tools/github_readme_sync/excluded_items.py
  tools/github_readme_sync/hierarchy.py
Labels: infrastructure, triaged

#127 Update benchmark results after migrating to AWS.
  benchmarks/results/montymeetsworld.csv
  benchmarks/results/ycb_10objs.csv
  benchmarks/results/ycb_77objs.csv
  benchmarks/results/ycb_unsupervised.csv
  docs/overview/benchmark-experiments.md
Labels: documentation, triaged

#66 Actions: Deploy preview docs
  .github/actions/pin_comment/action.yml
  .github/workflows/docs_preview.yml
Labels: infrastructure, triaged

#132 ci: pin cla-assistant@v1.0.0
  .github/workflows/cla.yml
Labels: infrastructure, triaged

#131 Added Vale linter for spelling and APA title case to the docs
  .vale.ini
  .vale/styles/Docs/Cliches.yml
  .vale/styles/Docs/Programming.yml
  .vale/styles/Docs/TitleCaseHeadings.yml
  .vale/styles/config/vocabularies/TBP/accept.txt
  README.md
  docs/community/our-licence-and-patent-pledge-explained.md
  docs/community/project-showcase.md
  docs/contributing/contributing-tutorials.md
  docs/contributing/contributing.md
  docs/contributing/documentation.md
  docs/contributing/guides-for-maintainers/triage.md
  docs/contributing/pull-requests.md
  docs/contributing/style-guide.md
  docs/contributing/ways-to-contribute-to-code.md
  docs/contributing/ways-to-contribute-to-code/identify-an-issue-to-work-on.md
  docs/contributing/why-contribute.md
  docs/future-work/cmp-hierarchy-improvements.md
  docs/future-work/cmp-hierarchy-improvements/run-analyze-experiments-in-multiobject-environment-looking-at-scene-graphs.md
  docs/future-work/cmp-hierarchy-improvements/send-similarity-encoding-object-id-to-next-level-test.md
  docs/future-work/framework-improvements/add-infrastructure-for-multiple-agents-that-move-independently.md
  docs/future-work/learning-module-improvements/use-off-object-observations.md
  docs/future-work/motor-system-improvements/reuse-hypothesis-testing-policy-target-points.md
  docs/future-work/motor-system-improvements/top-down-exploration-policy.md
  docs/future-work/project-roadmap.md
  docs/hierarchy.md
  docs/how-monty-works/connecting-lms-into-a-heterarchy.md
  docs/how-monty-works/evidence-based-learning-module.md
  docs/how-monty-works/how-learning-modules-work.md
  docs/how-monty-works/learning-module-outputs.md
  docs/how-to-use-monty/customizing-monty.md
  docs/how-to-use-monty/getting-started.md
  docs/how-to-use-monty/logging-and-analysis.md
  docs/how-to-use-monty/running-benchmarks.md
  docs/how-to-use-monty/tutorials/multiple-learning-modules.md
  docs/how-to-use-monty/tutorials/pretraining-a-model.md
  docs/how-to-use-monty/tutorials/running-your-first-experiment.md
  docs/how-to-use-monty/tutorials/unsupervised-continual-learning.md
  docs/overview/application-criteria.md
  docs/overview/benchmark-experiments.md
  docs/overview/faq-thousand-brains-project.md
  docs/overview/glossary.md
  docs/overview/vision-of-the-thousand-brains-project.md
  docs/overview/vision-of-the-thousand-brains-project/capabilities-of-the-system.md
  docs/overview/welcome-to-the-thousand-brains-project-documentation.md
  tools/github_readme_sync/hierarchy.py
Labels: documentation, triaged

#116 Don't use the semantic sensor by default
  benchmarks/configs/pretraining_experiments.py
  benchmarks/configs/ycb_experiments.py
  benchmarks/results/montymeetsworld.csv
  benchmarks/results/ycb_10objs.csv
  benchmarks/results/ycb_77objs.csv
  benchmarks/results/ycb_unsupervised.csv
  docs/how-to-use-monty/getting-started.md
  docs/overview/benchmark-experiments.md
  src/tbp/monty/frameworks/config_utils/make_dataset_configs.py
  src/tbp/monty/frameworks/environment_utils/transforms.py
  src/tbp/monty/frameworks/environments/embodied_data.py
  src/tbp/monty/frameworks/models/motor_policies.py
  tests/unit/habitat_transform_test.py
  tests/unit/policy_test.py
  tests/unit/run_parallel_test.py
Labels: triaged

#130 Tools: Clean up documentation previews
  .github/actions/get_preview_info/action.yml
  .github/workflows/cleanup_docs_preview.yml
  .github/workflows/docs_preview.yml
Labels: infrastructure, triaged

#138 Tools: Vale check
  .github/actions/vale_linter/action.yml
  .github/workflows/docs.yml
Labels: infrastructure, triaged

#140 Bug: Namespace the github action cache key so there are no collisions
  .github/workflows/cleanup_docs_preview.yml
Labels: infrastructure, triaged

#142 Tools: Docs Preview was Previewing the Main Branch
  .github/workflows/docs_preview.yml
Labels: infrastructure, triaged

#139 Docs: How to use Vale
  docs/contributing/documentation.md
Labels: documentation, triaged

#134 Allowing users to change the data dir
  docs/how-to-use-monty/getting-started.md
  src/tbp/monty/frameworks/config_utils/make_dataset_configs.py
  src/tbp/monty/frameworks/environment_utils/server.py
  src/tbp/monty/frameworks/environments/two_d_data.py
  src/tbp/monty/frameworks/run_env.py
Labels: enhancement, triaged

#125 Further technical faq updates
  .vale/styles/config/vocabularies/TBP/accept.txt
  docs/figures/how-monty-works/painting_vertumnus.png
  docs/how-monty-works/faq-monty.md
Labels: documentation, triaged

#145 Make Vale Dictionary Case-Sensitive
  .vale.ini
  .vale/styles/Docs/Programming.yml
  .vale/styles/config/vocabularies/TBP/accept.txt
  docs/contributing/contributing.md
  docs/contributing/documentation.md
  docs/contributing/guides-for-maintainers/triage.md
  docs/contributing/pull-requests.md
  docs/contributing/style-guide.md
  docs/contributing/ways-to-contribute-to-code.md
  docs/future-work/learning-module-improvements/implement-test-gnns-to-model-object-behaviors-states.md
  docs/how-monty-works/experiment.md
  docs/how-monty-works/faq-monty.md
  docs/how-to-use-monty/common-issues-and-how-to-fix-them.md
Labels: infrastructure, triaged

#126 Future Work minor updates
  docs/future-work/cmp-hierarchy-improvements/add-top-down-connections.md
  docs/future-work/cmp-hierarchy-improvements/figure-out-performance-measure-and-supervision-in-heterarchy.md
  docs/future-work/environment-improvements/make-dataset-to-test-compositional-objects.md
  docs/future-work/learning-module-improvements.md
  docs/future-work/learning-module-improvements/implement-and-test-rapid-evidence-decay-as-form-of-unsupervised-memory-resetting.md
  docs/future-work/learning-module-improvements/reinitialize-hypotheses-when-starting-to-recognize-a-new-object.md
  docs/future-work/motor-system-improvements.md
  docs/future-work/motor-system-improvements/bottom-up-exploration-policy-for-surface-agent.md
  docs/future-work/motor-system-improvements/implement-efficient-saccades-driven-by-model-free-and-model-based-signals.md
  docs/future-work/motor-system-improvements/implement-switching-between-learning-and-inference-focused-policies.md
  docs/future-work/motor-system-improvements/model-based-exploration-policy.md
  docs/future-work/motor-system-improvements/model-based-policy-to-recognize-an-object-before-moving-on-to-a-new-object.md
  docs/future-work/motor-system-improvements/policy-to-quickly-move-to-a-new-object.md
  docs/future-work/voting-improvements/generalize-voting-to-associative-connections.md
  docs/hierarchy.md
Labels: documentation, triaged

#147 refactor!: rename num_cpus to num_parallel for run_parallel
  src/tbp/monty/frameworks/config_utils/cmd_parser.py
  src/tbp/monty/frameworks/run_parallel.py
  tests/unit/run_parallel_test.py
Labels: triaged

#146 Patch off object (again)
  benchmarks/results/montymeetsworld.csv
  benchmarks/results/ycb_10objs.csv
  benchmarks/results/ycb_77objs.csv
  benchmarks/results/ycb_unsupervised.csv
  docs/overview/benchmark-experiments.md
  src/tbp/monty/frameworks/environments/embodied_data.py
  src/tbp/monty/frameworks/models/motor_policies.py
Labels: triaged

#143 Tools: Preview was using main (still)
  .github/workflows/docs_preview.yml
Labels: infrastructure, triaged

#150 RFC 6 Compartmentalize Simulator Code
  rfcs/0006_compartmentalize_simulator_code.md
  rfcs/0006_compartmentalize_simulator_code/near-term-code-roadmap-with-higlights.png
Labels: rfc:proposal, triaged

#151 refactor: remove habitat dependency from embodied_data
  src/tbp/monty/frameworks/environments/embodied_data.py
  src/tbp/monty/frameworks/environments/embodied_environment.py
  src/tbp/monty/frameworks/environments/habitat.py
  src/tbp/monty/frameworks/environments/real_robots.py
  src/tbp/monty/frameworks/environments/two_d_data.py
  src/tbp/monty/simulators/habitat/simulator.py
  tests/unit/embodied_data_test.py
Labels: triaged

#157 First Experiment Tutorial Updates
  docs/how-to-use-monty/getting-started.md
  docs/how-to-use-monty/tutorials/running-your-first-experiment.md
Labels: documentation, triaged

#155 Update model version numbers in docs
  docs/how-to-use-monty/getting-started.md
  docs/how-to-use-monty/logging-and-analysis.md
Labels: documentation, triaged

#149 refactor: compartmentalize habitat simulator dependent code
  benchmarks/configs/monty_world_experiments.py
  benchmarks/configs/pretraining_experiments.py
  benchmarks/configs/ycb_experiments.py
  src/tbp/monty/frameworks/config_utils/make_dataset_configs.py
  src/tbp/monty/frameworks/environments/two_d_data.py
  src/tbp/monty/simulators/habitat/configs.py
  src/tbp/monty/simulators/habitat/environment.py
  src/tbp/monty/simulators/habitat/environment_utils.py
  src/tbp/monty/simulators/habitat/simulator.py
  tests/unit/base_config_test.py
  tests/unit/evidence_lm_test.py
  tests/unit/graph_building_test.py
  tests/unit/graph_learning_test.py
  tests/unit/habitat_data_test.py
  tests/unit/policy_test.py
  tests/unit/run_parallel_test.py
  tests/unit/run_test.py
  tests/unit/sensor_module_test.py
Labels: triaged

#158 Don't create unused parallel processes.
  src/tbp/monty/frameworks/run_parallel.py
Labels: enhancement, triaged

#160 chore: clarifications in pre-training tutorial
  docs/how-to-use-monty/tutorials/pretraining-a-model.md
Labels: documentation, triaged

#156 docs: add minimal rfc template and update docs to accommodate
  docs/contributing/request-for-comments-rfc.md
  rfcs/0000_comprehensive_template.md
  rfcs/0000_minimal_template.md
Labels: documentation, triaged

#162 Tools: Insert a CSV into the docs
  benchmarks/results/montymeetsworld.csv
  benchmarks/results/ycb_10objs.csv
  benchmarks/results/ycb_77objs.csv
  benchmarks/results/ycb_unsupervised.csv
  docs/overview/benchmark-experiments.md
  tools/github_readme_sync/constants.py
  tools/github_readme_sync/hierarchy.py
  tools/github_readme_sync/readme.py
  tools/github_readme_sync/tests/hierarchy_test.py
  tools/github_readme_sync/tests/readme_test.py
  tools/github_readme_sync/upload.py
Labels: documentation, infrastructure, triaged
