Repository thousandbrainsproject/tbp.monty, pull requests merged in 2025-06, with the labels that each got.

#318 docs: benchmark updates for current code
  benchmarks/results/ycb_10objs.csv
  benchmarks/results/ycb_77objs.csv
Labels: triaged

#310 refactor!: SurfacePolicy touch_object phase always ends with MoveForward action
  benchmarks/results/ycb_10objs.csv
  benchmarks/results/ycb_77objs.csv
  benchmarks/results/ycb_unsupervised.csv
  benchmarks/results/ycb_unsupervised_inference.csv
  src/tbp/monty/frameworks/models/motor_policies.py
  tests/unit/policy_test.py
Labels: triaged

#289 feat: initial implementation of hypotheses resampling mixin
  src/tbp/monty/frameworks/models/evidence_matching.py
  src/tbp/monty/frameworks/models/feature_location_matching.py
  src/tbp/monty/frameworks/models/mixins/resampling_hypotheses_evidence.py
  src/tbp/monty/frameworks/models/no_reset_evidence_matching.py
  src/tbp/monty/frameworks/utils/evidence_matching.py
  src/tbp/monty/frameworks/utils/graph_matching_utils.py
  tests/unit/frameworks/models/mixins/resample_hypotheses_evidence_test.py
  tests/unit/frameworks/utils/evidence_matching_test.py
Labels: triaged

#317 refactor!: extract hypotheses update logic into HypothesesUpdaters
  benchmarks/configs/defaults.py
  benchmarks/configs/ycb_experiments.py
  benchmarks/results/ycb_10objs.csv
  docs/how-monty-works/evidence-based-learning-module/evidence-as-a-similarity-measure.md
  docs/how-to-use-monty/tutorials/multiple-learning-modules.md
  docs/how-to-use-monty/tutorials/running-inference-with-a-pretrained-model.md
  docs/how-to-use-monty/tutorials/unsupervised-continual-learning.md
  docs/how-to-use-monty/tutorials/using-monty-in-a-custom-application.md
  src/tbp/monty/frameworks/config_utils/config_args.py
  src/tbp/monty/frameworks/models/evidence_matching/__init__.py
  src/tbp/monty/frameworks/models/evidence_matching/feature_evidence/__init__.py
  src/tbp/monty/frameworks/models/evidence_matching/feature_evidence/calculator.py
  src/tbp/monty/frameworks/models/evidence_matching/feature_evidence/sdr_calculator.py
  src/tbp/monty/frameworks/models/evidence_matching/features_for_matching/__init__.py
  src/tbp/monty/frameworks/models/evidence_matching/features_for_matching/all_selector.py
  src/tbp/monty/frameworks/models/evidence_matching/features_for_matching/selector.py
  src/tbp/monty/frameworks/models/evidence_matching/graph_memory.py
  src/tbp/monty/frameworks/models/evidence_matching/hypotheses.py
  src/tbp/monty/frameworks/models/evidence_matching/hypotheses_displacer.py
  src/tbp/monty/frameworks/models/evidence_matching/hypotheses_updater.py
  src/tbp/monty/frameworks/models/evidence_matching/learning_module.py
  src/tbp/monty/frameworks/models/evidence_matching/model.py
  src/tbp/monty/frameworks/models/evidence_matching/resampling_hypotheses_updater.py
  src/tbp/monty/frameworks/models/evidence_sdr_matching.py
  src/tbp/monty/frameworks/models/graph_matching.py
  src/tbp/monty/frameworks/models/mixins/no_reset_evidence.py
  src/tbp/monty/frameworks/models/mixins/resampling_hypotheses_evidence.py
  src/tbp/monty/frameworks/models/no_reset_evidence_matching.py
  src/tbp/monty/frameworks/utils/evidence_matching.py
  src/tbp/monty/frameworks/utils/graph_matching_utils.py
  tests/unit/evidence_lm_test.py
  tests/unit/evidence_sdr_lm_test.py
  tests/unit/frameworks/models/evidence_matching/__init__.py
  tests/unit/frameworks/models/evidence_matching/resampling_hypotheses_updater_test.py
  tests/unit/frameworks/models/mixins/no_reset_evidence_test.py
  tests/unit/frameworks/utils/evidence_matching_test.py
  tests/unit/no_reset_evidence_lm_test.py
  tests/unit/policy_test.py
Labels: triaged

#314 refactor!: remove extraneous reset by refactoring reset out of __iter__
  benchmarks/results/ycb_10objs.csv
  src/tbp/monty/frameworks/environments/embodied_data.py
  tests/unit/embodied_data_test.py
  tests/unit/evidence_lm_test.py
  tests/unit/habitat_data_test.py
Labels: triaged

#320 chore: mypy configuration to recognize tbp.monty package
  pyproject.toml
Labels: infrastructure, triaged

#321 chore: initial uv environment setup
  docs/how-to-use-monty/getting-started.md
  pyproject.toml
  tests/unit/base_config_test.py
  tests/unit/custom_actions_test.py
  tests/unit/evidence_lm_test.py
  tests/unit/frameworks/actions/habitat/actuator_test.py
  tests/unit/frameworks/models/evidence_matching/resampling_hypotheses_updater_test.py
  tests/unit/graph_building_test.py
  tests/unit/graph_learning_test.py
  tests/unit/habitat_data_test.py
  tests/unit/habitat_sim_test.py
  tests/unit/no_reset_evidence_lm_test.py
  tests/unit/policy_test.py
  tests/unit/profile_experiment_mixin_test.py
  tests/unit/run_parallel_test.py
  tests/unit/run_test.py
  tests/unit/sensor_module_test.py
  tests/unit/tacto_test.py
  uv.lock
Labels: infrastructure, triaged

#319 refactor: SurfacePolicy does not consider touch_object for next actions
  benchmarks/results/ycb_10objs.csv
  benchmarks/results/ycb_77objs.csv
  src/tbp/monty/frameworks/models/motor_policies.py
  tests/unit/policy_test.py
Labels: triaged

#333 docs: update import paths in tutorials
  docs/how-to-use-monty/tutorials/multiple-learning-modules.md
  docs/how-to-use-monty/tutorials/running-inference-with-a-pretrained-model.md
  docs/how-to-use-monty/tutorials/unsupervised-continual-learning.md
  docs/how-to-use-monty/tutorials/using-monty-in-a-custom-application.md
Labels: documentation, triaged

#331 test: add workflow for uv environment
  .github/workflows/monty.yml
  uv.lock
Labels: triaged

#337 docs: add LEGO robot to project showcase
  .vale/styles/config/vocabularies/TBP/accept.txt
  docs/community/project-showcase.md
  docs/figures/community/lego_robot.png
Labels: documentation, triaged

#344 docs: include asdict and MyExperiments imports in all tutorials
  docs/how-to-use-monty/tutorials/multiple-learning-modules.md
  docs/how-to-use-monty/tutorials/running-inference-with-a-pretrained-model.md
  docs/how-to-use-monty/tutorials/unsupervised-continual-learning.md
Labels: documentation, triaged

#347 refactor!: move get_depth_at_center to PositioningProcedure
  src/tbp/monty/frameworks/environments/embodied_data.py
  src/tbp/monty/frameworks/models/motor_policies.py
Labels: triaged

#346 chore: extract Simulator protocol
  src/tbp/monty/frameworks/environments/embodied_environment.py
  src/tbp/monty/simulators/habitat/environment.py
  src/tbp/monty/simulators/habitat/simulator.py
  src/tbp/monty/simulators/simulator.py
Labels: triaged

#349 refactor!: raise ObjectNotVisible instead of returning None action
  src/tbp/monty/frameworks/environments/embodied_data.py
  src/tbp/monty/frameworks/models/motor_policies.py
Labels: triaged

#350 refactor: only increment dataloader _counter when on object
  src/tbp/monty/frameworks/environments/embodied_data.py
Labels: triaged

#352 style: no need for types in docstrings, they are automatic now
  pyproject.toml
  src/tbp/monty/frameworks/actions/actions.py
  src/tbp/monty/frameworks/config_utils/config_args.py
  src/tbp/monty/frameworks/config_utils/make_dataset_configs.py
  src/tbp/monty/frameworks/environment_utils/transforms.py
  src/tbp/monty/frameworks/environments/embodied_data.py
  src/tbp/monty/frameworks/environments/two_d_data.py
  src/tbp/monty/frameworks/experiments/monty_experiment.py
  src/tbp/monty/frameworks/models/displacement_matching.py
  src/tbp/monty/frameworks/models/evidence_matching/hypotheses_displacer.py
  src/tbp/monty/frameworks/models/evidence_matching/hypotheses_updater.py
  src/tbp/monty/frameworks/models/evidence_matching/learning_module.py
  src/tbp/monty/frameworks/models/evidence_matching/resampling_hypotheses_updater.py
  src/tbp/monty/frameworks/models/feature_location_matching.py
  src/tbp/monty/frameworks/models/goal_state_generation.py
  src/tbp/monty/frameworks/models/graph_matching.py
  src/tbp/monty/frameworks/models/mixins/no_reset_evidence.py
  src/tbp/monty/frameworks/models/monty_base.py
  src/tbp/monty/frameworks/models/motor_policies.py
  src/tbp/monty/frameworks/models/motor_system.py
  src/tbp/monty/frameworks/models/motor_system_state.py
  src/tbp/monty/frameworks/models/no_reset_evidence_matching.py
  src/tbp/monty/frameworks/models/object_model.py
  src/tbp/monty/frameworks/models/sensor_modules.py
  src/tbp/monty/frameworks/run_env.py
  src/tbp/monty/frameworks/run_parallel.py
  src/tbp/monty/frameworks/utils/dataclass_utils.py
  src/tbp/monty/frameworks/utils/evidence_matching.py
  src/tbp/monty/frameworks/utils/logging_utils.py
  src/tbp/monty/frameworks/utils/object_model_utils.py
  src/tbp/monty/frameworks/utils/plot_utils.py
  src/tbp/monty/frameworks/utils/spatial_arithmetics.py
  src/tbp/monty/simulators/habitat/actuator.py
  src/tbp/monty/simulators/habitat/agents.py
  src/tbp/monty/simulators/habitat/configs.py
  src/tbp/monty/simulators/habitat/environment_utils.py
  src/tbp/monty/simulators/habitat/sensors.py
  src/tbp/monty/simulators/habitat/simulator.py
  src/tbp/monty/simulators/simulator.py
  tests/unit/evidence_lm_test.py
  tests/unit/evidence_sdr_lm_test.py
  tests/unit/graph_building_test.py
  tests/unit/graph_learning_test.py
  tests/unit/habitat_sim_test.py
  tests/unit/no_reset_evidence_lm_test.py
  tests/unit/profile_experiment_mixin_test.py
  tests/unit/resources/unit_test_utils.py
  tools/generate_api_docs/README.md
  tools/generate_api_docs/source/conf.py
  tools/github_readme_sync/hierarchy.py
  tools/github_readme_sync/readme.py
  tools/plot/objects_evidence_over_time.py
  tools/plot/pose_error_over_time.py
  uv.lock
Labels: triaged

#357 chore: add correct percentage figure to plot tool
  tools/plot/cli.py
  tools/plot/correct_percentage_per_episode.py
  tools/plot/objects_evidence_over_time.py
  tools/plot/pose_error_over_time.py
  tools/plot/tests/correct_percentage_per_episode.py
Labels: triaged
