Repository thousandbrainsproject/tbp.monty, pull requests merged in 2025-08, with the labels that each got.

#411 chore: version 0.9.1
  src/tbp/monty/__init__.py
Labels: triaged

#376 RFC 12: Extended Goal State Functionality
  rfcs/0012_extended_goal_state_functionality.md
  rfcs/0012_extended_goal_state_functionality/architecture_overview.png
Labels: rfc:proposal, triaged

#416 test: less brittle config import test
  tests/unit/run_test.py
Labels: triaged

#413 refactor!: remove unused MontyBase.episodes
  src/tbp/monty/frameworks/models/monty_base.py
Labels: triaged

#412 refactor!: remove unused MontyBase.epochs
  src/tbp/monty/frameworks/models/monty_base.py
Labels: triaged

#418 docs: Fix for vale spell checking not catching misspellings
  .vale.ini
  .vale/styles/config/vocabularies/TBP/accept.txt
  docs/contributing/pull-requests/pull-request-flow.md
  docs/how-monty-works/policy.md
Labels: documentation, triaged

#405 rfc: RFC 14 Conducting Research While Building a Stable Platform
  rfcs/0014_conducting_research_while_building_a_stable_platform.md
Labels: rfc:proposal, triaged

#427 chore: version 0.10.0
  src/tbp/monty/__init__.py
Labels: triaged

#415 docs: added ultrasound project and hackathon video to the showcase page
  docs/community/project-showcase.md
  docs/figures/community/ultrasound_robot.jpg
  docs/how-to-use-monty/tutorials/using-monty-for-robotics.md
Labels: documentation, triaged

#431 docs: link to plain language explainers
  docs/overview/further-reading.md
Labels: documentation, triaged

#424 refactor!: Change getters to properties using @property in simulator.py.
  src/tbp/monty/simulators/habitat/environment.py
  src/tbp/monty/simulators/habitat/simulator.py
  src/tbp/monty/simulators/mujoco/simulator.py
  src/tbp/monty/simulators/simulator.py
  tests/unit/habitat_sim_test.py
  tests/unit/simulators/mujoco/mujoco_simulator_test.py
Labels: triaged

#447 refactor!: Dataclass class to dataclass_utils
  src/tbp/monty/frameworks/config_utils/config_args.py
  src/tbp/monty/frameworks/experiments/monty_experiment.py
  src/tbp/monty/frameworks/utils/dataclass_utils.py
  tests/unit/evidence_lm_test.py
  tests/unit/graph_learning_test.py
Labels: triaged
