Repository thousandbrainsproject/tbp.monty, pull requests merged in 2025-07, with the labels that each got.

#365 chore: Vedo interactive plot
  pyproject.toml
  tools/plot/README.md
  tools/plot/cli.py
  tools/plot/interactive_objects_evidence_over_time.py
  tools/plot/tests/interactive_objects_evidence_over_time.py
  uv.lock
Labels: triaged

#377 chore: version 0.8.0
  src/tbp/monty/__init__.py
Labels: triaged

#361 feat: MuJoCo sim, basic add and remove
  pyproject.toml
  src/tbp/monty/simulators/mujoco/__init__.py
  src/tbp/monty/simulators/mujoco/simulator.py
  tests/unit/simulators/__init__.py
  tests/unit/simulators/mujoco/__init__.py
  tests/unit/simulators/mujoco/mujoco_simulator_test.py
  uv.lock
Labels: triaged

#380 docs: delete reference to non-existent class
  docs/how-monty-works/how-learning-modules-work.md
Labels: documentation, triaged

#389 docs: Fix broken tutorial
  .vale/styles/config/vocabularies/TBP/accept.txt
  docs/how-to-use-monty/tutorials/running-your-first-experiment.md
Labels: documentation, triaged

#384 refactor: dynamically collect experiment dataclasses and eliminate duplication
  benchmarks/configs/names.py
Labels: triaged

#383 docs: remove reference to non-existent SensorModuleBase
  docs/how-monty-works/observations-transforms-sensor-modules.md
Labels: documentation, triaged

#392 docs: code organization guide
  .vale/styles/config/vocabularies/TBP/accept.txt
  docs/contributing/style-guide.md
  docs/contributing/style-guide/code-style-guide.md
  docs/hierarchy.md
Labels: documentation, triaged

#394 chore: change point normal to surface normal
  benchmarks/configs/defaults.py
  benchmarks/configs/pretraining_experiments.py
  docs/future-work/motor-system-improvements/model-based-exploration-policy.md
  docs/how-monty-works/evidence-based-learning-module.md
  docs/how-monty-works/how-learning-modules-work.md
  docs/how-monty-works/observations-transforms-sensor-modules.md
  docs/how-monty-works/policy.md
  docs/how-to-use-monty/common-issues-and-how-to-fix-them.md
  docs/how-to-use-monty/logging-and-analysis.md
  docs/how-to-use-monty/tutorials/using-monty-for-robotics.md
  docs/how-to-use-monty/tutorials/using-monty-in-a-custom-application.md
  docs/overview/benchmark-experiments.md
  src/tbp/monty/frameworks/environment_utils/transforms.py
  src/tbp/monty/frameworks/environments/embodied_data.py
  src/tbp/monty/frameworks/models/displacement_matching.py
  src/tbp/monty/frameworks/models/evidence_matching/hypotheses_displacer.py
  src/tbp/monty/frameworks/models/evidence_matching/hypotheses_updater.py
  src/tbp/monty/frameworks/models/evidence_matching/learning_module.py
  src/tbp/monty/frameworks/models/evidence_matching/resampling_hypotheses_updater.py
  src/tbp/monty/frameworks/models/feature_location_matching.py
  src/tbp/monty/frameworks/models/goal_state_generation.py
  src/tbp/monty/frameworks/models/motor_policies.py
  src/tbp/monty/frameworks/models/sensor_modules.py
  src/tbp/monty/frameworks/models/states.py
  src/tbp/monty/frameworks/utils/graph_matching_utils.py
  src/tbp/monty/frameworks/utils/object_model_utils.py
  src/tbp/monty/frameworks/utils/plot_utils.py
  src/tbp/monty/frameworks/utils/sensor_processing.py
  src/tbp/monty/frameworks/utils/spatial_arithmetics.py
  tests/unit/evidence_lm_test.py
  tests/unit/policy_test.py
Labels: triaged

#391 build: pin torch version in pyproject.toml so that pip respects it
  pyproject.toml
Labels: infrastructure, triaged

#375 fix: eliminate numpy warnings with empty array checks
  src/tbp/monty/frameworks/loggers/graph_matching_loggers.py
  src/tbp/monty/frameworks/models/buffer.py
Labels: triaged

#374 refactor: improve buffer channel selection logic
  src/tbp/monty/frameworks/models/buffer.py
Labels: triaged
