Repository thousandbrainsproject/tbp.monty, pull requests merged in 2025-09, with the labels that each got.

#444 refactor: update get_edge_index to use vector operations
  src/tbp/monty/frameworks/environment_utils/graph_utils.py
Labels: triaged

#456 docs: emphasize Maintainers cannot assing PRs to themselves
  docs/contributing/guides-for-maintainers/triage.md
Labels: documentation, triaged

#435 rfc: RFC 17 Guidance on the use of LLMS
  .vale/styles/config/vocabularies/TBP/accept.txt
  rfcs/0017_guidance_on_using_llms.md
  rfcs/0017_guidance_on_using_llms/commenting_example.png
Labels: rfc:proposal, triaged

#458 chore: version 0.11.0
  src/tbp/monty/__init__.py
Labels: triaged

#471 refactor: correcting spelling for euclidean
  src/tbp/monty/frameworks/models/object_model.py
  src/tbp/monty/frameworks/utils/graph_matching_utils.py
Labels: triaged

#465 updated environment to allow mkl dep for mac intel
  environment.yml
Labels: infrastructure, triaged

#476 feat: Live plotting option for all MontyExperiment instances
  src/tbp/monty/frameworks/experiments/data_collection_experiments.py
  src/tbp/monty/frameworks/experiments/monty_experiment.py
  src/tbp/monty/frameworks/experiments/object_recognition_experiments.py
  src/tbp/monty/frameworks/experiments/pretraining_experiments.py
  src/tbp/monty/frameworks/utils/live_plotter.py
Labels: triaged

#479 feat!: add locations to resampling telemetry
  src/tbp/monty/frameworks/models/evidence_matching/resampling_hypotheses_updater.py
  src/tbp/monty/frameworks/models/mixins/no_reset_evidence.py
  tests/unit/frameworks/models/mixins/no_reset_evidence_test.py
Labels: triaged

#482 docs: update Bluesky profile path
  .vale/styles/config/vocabularies/TBP/accept.txt
  README.md
  docs/contributing/contributing.md
  docs/overview/welcome-to-the-thousand-brains-project-documentation.md
  tools/generate_api_docs/source/conf.py
Labels: documentation, triaged

#448 refactor!: Move Dataset functionality into EnvironmentDataloader
  benchmarks/configs/monty_world_experiments.py
  benchmarks/configs/monty_world_habitat_experiments.py
  benchmarks/configs/pretraining_experiments.py
  benchmarks/configs/ycb_experiments.py
  src/tbp/monty/frameworks/environments/embodied_data.py
  src/tbp/monty/frameworks/environments/embodied_environment.py
  src/tbp/monty/frameworks/experiments/monty_experiment.py
  tests/unit/base_config_test.py
  tests/unit/embodied_data_test.py
  tests/unit/evidence_lm_test.py
  tests/unit/frameworks/models/evidence_matching/resampling_hypotheses_updater_test.py
  tests/unit/graph_building_test.py
  tests/unit/graph_learning_test.py
  tests/unit/habitat_data_test.py
  tests/unit/no_reset_evidence_lm_test.py
  tests/unit/policy_test.py
  tests/unit/profile_experiment_mixin_test.py
  tests/unit/run_parallel_test.py
  tests/unit/run_test.py
  tests/unit/sensor_module_test.py
Labels: triaged

#457 chore: upgrade pytorch and remove torchvision
  environment.yml
  environment_arm64.yml
  pyproject.toml
  recipe/meta.yaml
  tools/generate_api_docs/source/conf.py
  uv.lock
Labels: infrastructure, triaged

#481 feat: Add mlh to live plot + fix text
  src/tbp/monty/frameworks/utils/live_plotter.py
Labels: triaged
