Repository thousandbrainsproject/tbp.monty, pull requests merged in 2025-04, with the labels that each got.

#220 refactor!: MontyExperiment context manager part 2
  src/tbp/monty/frameworks/experiments/monty_experiment.py
  src/tbp/monty/frameworks/experiments/pretraining_experiments.py
  src/tbp/monty/frameworks/run.py
  src/tbp/monty/frameworks/run_parallel.py
  tests/unit/base_config_test.py
  tests/unit/evidence_lm_test.py
  tests/unit/graph_building_test.py
  tests/unit/graph_learning_test.py
  tests/unit/policy_test.py
  tests/unit/profile_experiment_mixin_test.py
  tests/unit/run_parallel_test.py
  tests/unit/sensor_module_test.py
Labels: triaged

#230 chore: version 0.2.0
  src/tbp/monty/__init__.py
Labels: triaged

#231 refactor: first movement logic in GraphLM
  src/tbp/monty/frameworks/models/displacement_matching.py
  src/tbp/monty/frameworks/models/graph_matching.py
  tests/unit/evidence_sdr_lm_test.py
Labels: triaged

#229 chore: updating ruff version and removing ANN101 and ANN102 from ignore
  pyproject.toml
  src/tbp/monty/frameworks/models/motor_policies.py
  src/tbp/monty/frameworks/utils/transform_utils.py
  src/tbp/monty/simulators/tacto/__init__.py
Labels: infrastructure, triaged

#233 chore: clean up ruff's ignore list to remove rules that pass
  pyproject.toml
Labels: infrastructure, triaged

#221 feat: YCB testbed for removing reset between episodes
  benchmarks/configs/load.py
  benchmarks/configs/names.py
  benchmarks/configs/unsupervised_inference_experiments.py
  benchmarks/results/ycb_unsupervised_inference.csv
  docs/overview/benchmark-experiments.md
  src/tbp/monty/frameworks/models/buffer.py
  src/tbp/monty/frameworks/models/goal_state_generation.py
  src/tbp/monty/frameworks/models/no_reset_evidence_matching.py
  tests/unit/no_reset_evidence_lm_test.py
Labels: enhancement, triaged

#232 refactor!: remove unused MotorSystem.update method
  src/tbp/monty/frameworks/models/motor_policies.py
Labels: triaged

#235 refactor!: remove setting unused MotorSystem.step_type attribute
  src/tbp/monty/frameworks/models/monty_base.py
Labels: triaged

#239 refactor: do not add extra params to _add_detailed_stats override
  src/tbp/monty/frameworks/models/evidence_matching.py
Labels: triaged

#234 refactor!: motor policies are an attribute of MotorSystem
  benchmarks/configs/pretraining_experiments.py
  benchmarks/make_detailed_follow_up_configs.py
  docs/how-to-use-monty/tutorials/multiple-learning-modules.md
  src/tbp/monty/frameworks/config_utils/config_args.py
  src/tbp/monty/frameworks/environments/embodied_data.py
  src/tbp/monty/frameworks/experiments/data_collection_experiments.py
  src/tbp/monty/frameworks/experiments/monty_experiment.py
  src/tbp/monty/frameworks/experiments/object_recognition_experiments.py
  src/tbp/monty/frameworks/loggers/graph_matching_loggers.py
  src/tbp/monty/frameworks/models/evidence_matching.py
  src/tbp/monty/frameworks/models/graph_matching.py
  src/tbp/monty/frameworks/models/monty_base.py
  src/tbp/monty/frameworks/models/motor_policies.py
  src/tbp/monty/frameworks/models/motor_system.py
  src/tbp/monty/frameworks/utils/follow_up_configs.py
  tests/unit/embodied_data_test.py
  tests/unit/evidence_lm_test.py
  tests/unit/graph_learning_test.py
  tests/unit/habitat_data_test.py
  tests/unit/policy_test.py
Labels: triaged

#241 chore: version 0.3.0
  src/tbp/monty/__init__.py
Labels: triaged

#243 chore: only strings should be added to sys.path
  tools/generate_api_docs/source/conf.py
  tools/github_readme_sync/cli.py
Labels: triaged

#227 feat: unsupervised inference logging and plotting functions
  benchmarks/configs/unsupervised_inference_experiments.py
  src/tbp/monty/frameworks/models/graph_matching.py
  src/tbp/monty/frameworks/models/mixins/__init__.py
  src/tbp/monty/frameworks/models/mixins/no_reset_evidence.py
  src/tbp/monty/frameworks/models/no_reset_evidence_matching.py
  src/tbp/monty/frameworks/plots/__init__.py
  src/tbp/monty/frameworks/plots/no_reset_evidence.py
  tests/unit/no_reset_evidence_lm_test.py
Labels: enhancement, triaged

#245 fix: Fix Omniglot Environment
  src/tbp/monty/frameworks/environments/two_d_data.py
  src/tbp/monty/frameworks/experiments/pretraining_experiments.py
  src/tbp/monty/frameworks/models/sensor_modules.py
Labels: triaged

#244 chore: initial implementation of plot tool
  tools/plot/README.md
  tools/plot/__init__.py
  tools/plot/cli.py
  tools/plot/objects_evidence_over_time.py
  tools/plot/pose_error_over_time.py
  tools/plot/tests/__init__.py
  tools/plot/tests/objects_evidence_over_time.py
  tools/plot/tests/pose_error_over_time_test.py
Labels: triaged

#247 refactor!: remove plot functionality subsumed by the plot tool
  src/tbp/monty/frameworks/plots/__init__.py
  src/tbp/monty/frameworks/plots/no_reset_evidence.py
Labels: triaged

#250 refactor: enforce TheoreticalLimitLMLoggingMixin compatibility requirement
  src/tbp/monty/frameworks/models/mixins/no_reset_evidence.py
  tests/unit/frameworks/models/mixins/__init__.py
  tests/unit/frameworks/models/mixins/no_reset_evidence_test.py
Labels: triaged

#249 refactor: pose error calculation logic
  src/tbp/monty/frameworks/models/mixins/no_reset_evidence.py
  src/tbp/monty/frameworks/utils/logging_utils.py
  tests/unit/frameworks/utils/logging_utils_test.py
Labels: triaged

#246 RFC 10 Conventional Commits
  rfcs/0010_conventional_commits.md
Labels: rfc:proposal, triaged

#255 refactor: reduce dataloader and motor system policy state interactions
  src/tbp/monty/frameworks/environments/embodied_data.py
Labels: triaged

#252 fix: monty meets world streaming code
  benchmarks/configs/monty_world_experiments.py
  src/tbp/monty/frameworks/environment_utils/server.py
  src/tbp/monty/frameworks/environments/two_d_data.py
Labels: triaged

#259 chore: move channel mapper unit tests
  tests/unit/frameworks/utils/evidence_matching_test.py
Labels: triaged

#265 refactor: remove unncessary parentheses (UP034)
  pyproject.toml
  src/tbp/monty/frameworks/environments/two_d_data.py
  src/tbp/monty/frameworks/models/evidence_matching.py
  src/tbp/monty/frameworks/utils/plot_utils.py
  src/tbp/monty/frameworks/utils/spatial_arithmetics.py
  tests/unit/evidence_sdr_lm_test.py
Labels: triaged

#270 fix: MontyBase._step_learning_modules now works
  src/tbp/monty/frameworks/models/monty_base.py
Labels: triaged

#260 docs: Add videos and links
  README.md
  docs/future-work/project-roadmap.md
  docs/how-monty-works/evidence-based-learning-module.md
  docs/how-monty-works/evidence-based-learning-module/evidence-as-a-similarity-measure.md
  docs/how-to-use-monty/getting-started.md
  docs/overview/application-criteria.md
  docs/overview/architecture-overview.md
  docs/overview/architecture-overview/bringing-it-together.md
  docs/overview/architecture-overview/cortical-messaging-protocol.md
  docs/overview/architecture-overview/learning-modules.md
  docs/overview/architecture-overview/other-aspects.md
  docs/overview/architecture-overview/sensor-modules.md
  docs/overview/benchmark-experiments.md
  docs/overview/further-reading.md
  docs/overview/vision-of-the-thousand-brains-project/short-term-goals.md
  docs/overview/welcome-to-the-thousand-brains-project-documentation.md
Labels: documentation, triaged

#263 refactor!: state is stored in motor system instead of policies
  src/tbp/monty/frameworks/environments/embodied_data.py
  src/tbp/monty/frameworks/models/monty_base.py
  src/tbp/monty/frameworks/models/motor_policies.py
  src/tbp/monty/frameworks/models/motor_system.py
  src/tbp/monty/frameworks/models/motor_system_state.py
  tests/unit/frameworks/models/motor_policies_test.py
  tests/unit/policy_test.py
Labels: triaged

#274 refactor: enable most comprehension lints
  benchmarks/configs/follow_ups/__init__.py
  benchmarks/configs/follow_ups/names.py
  benchmarks/configs/load.py
  benchmarks/configs/monty_world_experiments.py
  benchmarks/configs/names.py
  pyproject.toml
  src/tbp/monty/frameworks/config_utils/config_args.py
  src/tbp/monty/frameworks/config_utils/make_dataset_configs.py
  src/tbp/monty/frameworks/experiments/profile.py
  src/tbp/monty/frameworks/loggers/graph_matching_loggers.py
  src/tbp/monty/frameworks/loggers/monty_handlers.py
  src/tbp/monty/frameworks/loggers/wandb_handlers.py
  src/tbp/monty/frameworks/models/buffer.py
  src/tbp/monty/frameworks/models/displacement_matching.py
  src/tbp/monty/frameworks/models/evidence_matching.py
  src/tbp/monty/frameworks/models/evidence_sdr_matching.py
  src/tbp/monty/frameworks/models/feature_location_matching.py
  src/tbp/monty/frameworks/models/graph_matching.py
  src/tbp/monty/frameworks/models/mixins/no_reset_evidence.py
  src/tbp/monty/frameworks/models/motor_system_state.py
  src/tbp/monty/frameworks/models/object_model.py
  src/tbp/monty/frameworks/models/sensor_modules.py
  src/tbp/monty/frameworks/run_parallel.py
  src/tbp/monty/frameworks/utils/dataclass_utils.py
  src/tbp/monty/frameworks/utils/follow_up_configs.py
  src/tbp/monty/frameworks/utils/logging_utils.py
  src/tbp/monty/frameworks/utils/object_model_utils.py
  src/tbp/monty/simulators/habitat/simulator.py
  tests/unit/base_config_test.py
  tests/unit/frameworks/actions/habitat/actuator_test.py
  tests/unit/graph_learning_test.py
  tests/unit/policy_test.py
  tests/unit/resources/unit_test_utils.py
Labels: triaged

#261 docs: additional formatting, structuring and notes
  docs/how-monty-works/observations-transforms-sensor-modules.md
  docs/overview/application-criteria.md
  docs/overview/benchmark-experiments.md
  docs/overview/vision-of-the-thousand-brains-project/long-term-goals-and-principles.md
Labels: documentation, triaged

#276 style: enable ruff format checking
  .github/workflows/monty.yml
  .github/workflows/tools.yml
  docs/contributing/pull-requests.md
  src/tbp/monty/frameworks/config_utils/make_dataset_configs.py
  src/tbp/monty/frameworks/environments/embodied_environment.py
  src/tbp/monty/frameworks/experiments/object_recognition_experiments.py
  src/tbp/monty/frameworks/experiments/pretraining_experiments.py
  src/tbp/monty/frameworks/experiments/profile.py
  src/tbp/monty/frameworks/loggers/wandb_handlers.py
  src/tbp/monty/frameworks/models/evidence_matching.py
  src/tbp/monty/frameworks/models/evidence_sdr_matching.py
  src/tbp/monty/frameworks/models/feature_location_matching.py
  src/tbp/monty/frameworks/models/goal_state_generation.py
  src/tbp/monty/frameworks/models/graph_matching.py
  src/tbp/monty/frameworks/models/monty_base.py
  src/tbp/monty/frameworks/models/object_model.py
  src/tbp/monty/frameworks/models/sensor_modules.py
  src/tbp/monty/frameworks/models/states.py
  src/tbp/monty/frameworks/utils/logging_utils.py
  src/tbp/monty/frameworks/utils/object_model_utils.py
  src/tbp/monty/frameworks/utils/plot_utils.py
  src/tbp/monty/simulators/habitat/simulator.py
  tests/unit/base_config_test.py
  tests/unit/evidence_lm_test.py
  tests/unit/graph_building_test.py
  tests/unit/graph_learning_test.py
  tests/unit/policy_test.py
  tests/unit/profile_experiment_mixin_test.py
  tests/unit/resources/unit_test_utils.py
  tools/github_readme_sync/req.py
  tools/github_readme_sync/tests/file_test.py
Labels: triaged

#275 refactor!: GetGoodView positioning procedure
  src/tbp/monty/frameworks/config_utils/make_dataset_configs.py
  src/tbp/monty/frameworks/environments/embodied_data.py
  src/tbp/monty/frameworks/models/motor_policies.py
  tests/unit/evidence_lm_test.py
  tests/unit/feature_flags.py
  tests/unit/graph_building_test.py
  tests/unit/graph_learning_test.py
  tests/unit/no_reset_evidence_lm_test.py
  tests/unit/policy_test.py
  tests/unit/run_parallel_test.py
  tests/unit/sensor_module_test.py
Labels: triaged

#277 chore: ignore reformatting in git-blame
  .git-blame-ignore-revs
Labels: infrastructure, triaged

#269 test: refactor 5LM test to use fake observations
  tests/unit/graph_learning_test.py
  tests/unit/resources/unit_test_utils.py
Labels: triaged

#280 chore: add assignee approvals check
  .github/workflows/assignee-approval.yml
Labels: infrastructure, triaged

#279 test: use GPU runner for monty tests
  .github/workflows/monty.yml
Labels: infrastructure, triaged

#282 revert: add assignee approvals check
  .github/workflows/assignee-approval.yml
Labels: triaged

#284 docs: Add Theory Documentation + Object Behavior Disclosure
  .vale/styles/config/vocabularies/TBP/accept.txt
  docs/figures/theory/behavior_models.png
  docs/hierarchy.md
  docs/theory/recent-progress.md
  docs/theory/recent-progress/object-behaviors.md
  docs/theory/theory-overview.md
Labels: documentation, triaged

#286 ci: don't trigger monty tests when vale config changes
  .github/actions/should_run_monty/check_changed_files.sh
Labels: infrastructure, triaged
