Repository thousandbrainsproject/tbp.monty, pull requests merged in 2025-02, with the labels that each got.

#168 Fix: Don't run docs preview when the PR is closed, or merged
  .github/workflows/docs_preview.yml
Labels: triaged

#167 Docs: Inserting tables
  docs/contributing/style-guide.csv
  docs/contributing/style-guide.md
Labels: documentation, triaged

#171 Docs: Add warning about windows / linux
  docs/how-to-use-monty/getting-started.md
Labels: documentation, triaged

#141 Illustrations for vision page
  docs/figures/overview/brain_balloons_day.png
  docs/figures/overview/embodied_sensorimotor_learning.png
  docs/figures/overview/reference_frames_illustration.png
  docs/overview/vision-of-the-thousand-brains-project.md
Labels: documentation, triaged

#173 Fix: Dangling docs preview
  .github/workflows/cleanup_docs_preview.yml
Labels: triaged

#172 Deploy docs on push to main
  .github/actions/get_preview_info/action.yml
  .github/workflows/docs_deploy.yml
Labels: triaged

#174 Docs: Snippets
  docs/future-work/cmp-hierarchy-improvements.md
  docs/future-work/environment-improvements.md
  docs/future-work/framework-improvements.md
  docs/future-work/learning-module-improvements.md
  docs/future-work/motor-system-improvements.md
  docs/future-work/oss-communication-improvements.md
  docs/future-work/sensor-module-improvements.md
  docs/future-work/voting-improvements.md
  docs/snippets/contributing-tasks.md
  tools/github_readme_sync/readme.py
  tools/github_readme_sync/tests/readme_test.py
Labels: triaged

#178 Chore: Build the docs when benchmarks/results/** change
  .github/workflows/docs_preview.yml
Labels: infrastructure, triaged

#177 Fix: incorrect header row in CSV for Unsupervised Benchmarks
  benchmarks/results/ycb_unsupervised.csv
Labels: documentation, triaged

#179 Dont require unused dataloaders
  benchmarks/configs/monty_world_experiments.py
  benchmarks/configs/monty_world_habitat_experiments.py
  benchmarks/configs/pretraining_experiments.py
  benchmarks/configs/ycb_experiments.py
  src/tbp/monty/frameworks/experiments/monty_experiment.py
Labels: triaged

#180 docs: document github action workflow file name convention
  docs/contributing/style-guide.md
Labels: documentation, triaged

#182 Docs: fix a broken link due to missing .md extension
  docs/how-monty-works/faq-monty.md
Labels: documentation, triaged

#183 ci: only run actions in thousandbrains tbp.monty repo
  .github/workflows/cleanup_docs_preview.yml
  .github/workflows/docs_deploy.yml
  .github/workflows/docs_preview.yml
Labels: infrastructure, triaged

#186 RFC 7 Monty Versioning
  rfcs/0007_monty_versioning.md
Labels: rfc:proposal, triaged

#190 build: reset version to 0.0.0 to satisfy conda constraint
  src/tbp/monty/__init__.py
Labels: infrastructure, triaged

#188 docs: additional context for evidence_update_threshold
  src/tbp/monty/frameworks/models/evidence_matching.py
Labels: documentation, triaged

#187 add DetailedWandbTableStatsHandler to reduce unnesscessary wandb logging
  src/tbp/monty/frameworks/loggers/wandb_handlers.py
Labels: triaged

#193 build: conda build
  .github/actions/version_updated/action.yml
  .github/actions/version_updated/check_version_updated.sh
  .github/workflows/monty_publish.yml
  recipe/conda_build_config.yaml
  recipe/meta.yaml
Labels: infrastructure, triaged

#194 build: set correct working-directory for version_updated action
  .github/actions/version_updated/action.yml
Labels: infrastructure, triaged

#195 build: need fetch-depth=2 for git diff commit^1 comparison
  .github/workflows/monty_publish.yml
Labels: infrastructure, triaged

#198 chore: version 0.0.1
  src/tbp/monty/__init__.py
Labels: triaged

#199 build: publish Monty builds to anaconda.org
  .github/workflows/monty_publish.yml
Labels: infrastructure, triaged

#201 build: remove explicit mask that maybe causes 401
  .github/workflows/monty_publish.yml
Labels: infrastructure, triaged

#202 build: set target platform before capturing (platform-dependent) path
  .github/workflows/monty_publish.yml
Labels: infrastructure, triaged
