Repository thousandbrainsproject/tbp.monty, pull requests merged in 2025-03, with the labels that each got.

#203 build: tag version commit with version tag
  .github/actions/version_updated/action.yml
  .github/actions/version_updated/check_version_updated.sh
  .github/workflows/monty_publish.yml
Labels: infrastructure, triaged

#204 build: source dependencies from conda
  environment.yml
  environment_arm64.yml
  pyproject.toml
  recipe/meta.yaml
Labels: infrastructure, triaged

#159 RFC 8 Reorganization of Repositories
  rfcs/0008_reorganize_repositories.md
Labels: rfc:proposal, triaged

#175 Edit this page
  docs/snippets/edit-this-page.md
  tools/github_readme_sync/readme.py
  tools/github_readme_sync/tests/readme_test.py
Labels: documentation, triaged

#209 chore: sanitize snippets
  docs/contributing/pull-requests/pull-request-flow.md
  docs/figures/contributing/pull_request_flow.md
  docs/snippets/edit-this-page.md
  tools/github_readme_sync/readme.py
  tools/github_readme_sync/tests/readme_test.py
  tools/github_readme_sync/upload.py
Labels: triaged

#211 build: pin numpy version, later ones are missing np.long
  environment.yml
  environment_arm64.yml
  recipe/meta.yaml
Labels: triaged

#212 chore: version 0.0.3
  src/tbp/monty/__init__.py
Labels: triaged

#213 chore: fix for bug where glossary has old description
  docs/overview/glossary.md
  tools/github_readme_sync/md.py
  tools/github_readme_sync/readme.py
  tools/github_readme_sync/tests/md_test.py
  tools/github_readme_sync/tests/readme_test.py
Labels: documentation, triaged

#196 RFC 9 Hypotheses Resampling
  rfcs/0009_hypotheses_resampling.md
  rfcs/0009_hypotheses_resampling/high_level_code_change.png
  rfcs/0009_hypotheses_resampling/monty_reset_logic.png
  rfcs/0009_hypotheses_resampling/no_resampling.png
  rfcs/0009_hypotheses_resampling/resampling_banana_mug.png
  rfcs/0009_hypotheses_resampling/terminal_state_reached.png
Labels: rfc:proposal, triaged

#216 refactor: `BufferEncoder` registration for types and encoders
  src/tbp/monty/frameworks/models/buffer.py
  tests/unit/frameworks/models/__init__.py
  tests/unit/frameworks/models/buffer_encoder_test.py
Labels: enhancement, triaged

#218 chore: update BufferEncoder tests
  src/tbp/monty/frameworks/models/buffer.py
  tests/unit/frameworks/models/buffer_encoder_test.py
  tests/unit/frameworks/models/fakes/__init__.py
  tests/unit/frameworks/models/fakes/encoder_classes.py
  tests/unit/frameworks/models/fakes/encoders.py
Labels: triaged

#210 minor modifications to evidence updating
  src/tbp/monty/frameworks/models/evidence_matching.py
  src/tbp/monty/frameworks/utils/evidence_matching.py
  tests/unit/channel_mapper_test.py
  tests/unit/evidence_lm_test.py
Labels: triaged

#217 refactor: Avoid possible locations double initialization.
  src/tbp/monty/frameworks/models/evidence_matching.py
  src/tbp/monty/frameworks/models/object_model.py
Labels: triaged

#222 chore: add tests for ProfileExperimentMixin
  src/tbp/monty/frameworks/experiments/profile.py
  tests/unit/profile_experiment_mixin_test.py
Labels: triaged

#219 feat: Logging `GoalState` objects
  src/tbp/monty/frameworks/models/goal_state_generation.py
  src/tbp/monty/frameworks/models/states.py
  tests/unit/frameworks/models/state_test.py
  tests/unit/resources/unit_test_utils.py
Labels: enhancement, triaged

#225 chore: version 0.1.0
  src/tbp/monty/__init__.py
Labels: triaged

#223 Update documentation.md
  docs/contributing/documentation.md
Labels: documentation, triaged

#226 docs: install rosetta on apple silicon instructions
  docs/how-to-use-monty/getting-started.md
Labels: documentation, triaged
