Repository thousandbrainsproject/tbp.monty, pull requests merged in 2025-05, with the labels that each got.

#285 docs: RFC 10 Conventional Commits callouts for Maintainers
  docs/contributing/pull-requests/pull-request-flow.md
Labels: documentation, triaged

#283 fix: GetGoodView positioning procedure matches previous code
  src/tbp/monty/frameworks/config_utils/make_dataset_configs.py
  src/tbp/monty/frameworks/environments/embodied_data.py
  src/tbp/monty/frameworks/models/motor_policies.py
Labels: triaged

#290 chore: white background for image
  docs/figures/theory/behavior_models.png
Labels: documentation, triaged

#287 refactor!: data loaders use GetGoodView positioning procedure only
  docs/how-monty-works/policy.md
  src/tbp/monty/frameworks/config_utils/make_dataset_configs.py
  src/tbp/monty/frameworks/environments/embodied_data.py
  src/tbp/monty/frameworks/models/motor_policies.py
  tests/unit/evidence_lm_test.py
  tests/unit/feature_flags.py
  tests/unit/graph_building_test.py
  tests/unit/graph_learning_test.py
  tests/unit/no_reset_evidence_lm_test.py
  tests/unit/policy_test.py
  tests/unit/run_parallel_test.py
  tests/unit/sensor_module_test.py
Labels: triaged

#293 chore: version 0.4.0
  src/tbp/monty/__init__.py
Labels: triaged

#295 ci: pin python version for monty_publish workflow
  .github/workflows/monty_publish.yml
Labels: infrastructure, triaged

#294 rfc: update RFC 10 examples to include PR number
  rfcs/0010_conventional_commits.md
Labels: rfc:proposal, triaged

#298 chore: ignore .envrc files for direnv
  .gitignore
Labels: triaged

#300 refactor: remove unused else case
  src/tbp/monty/frameworks/experiments/monty_experiment.py
Labels: triaged

#302 refactor: remove unused _amount prop forgotten during RFC 4 refactor
  src/tbp/monty/frameworks/environments/embodied_data.py
Labels: triaged

#303 fix: motor_only_step flag is now always True for motor-only steps
  benchmarks/results/ycb_10objs.csv
  benchmarks/results/ycb_77objs.csv
  benchmarks/results/ycb_unsupervised.csv
  benchmarks/results/ycb_unsupervised_inference.csv
  docs/overview/benchmark-experiments.md
  pyproject.toml
  src/tbp/monty/frameworks/environments/embodied_data.py
  tests/unit/policy_test.py
Labels: triaged

#304 chore: version 0.5.0
  src/tbp/monty/__init__.py
Labels: triaged

#301 refactor: restructuring of _update_evidence
  src/tbp/monty/frameworks/models/evidence_matching.py
  src/tbp/monty/frameworks/utils/evidence_matching.py
  tests/unit/frameworks/utils/evidence_matching_test.py
Labels: triaged

#305 fix: SurfacePolicy touch_object and dynamic_call no longer interfere
  benchmarks/results/ycb_10objs.csv
  benchmarks/results/ycb_77objs.csv
  benchmarks/results/ycb_unsupervised.csv
  benchmarks/results/ycb_unsupervised_inference.csv
  src/tbp/monty/frameworks/environments/embodied_data.py
  src/tbp/monty/frameworks/models/motor_policies.py
  tests/unit/policy_test.py
Labels: triaged

#308 docs: Add mmw comments
  benchmarks/configs/monty_world_habitat_experiments.py
  src/tbp/monty/frameworks/environments/two_d_data.py
Labels: documentation, triaged

#307 chore: print config by default
  src/tbp/monty/frameworks/run.py
Labels: triaged

#309 chore: add .rsyncignore to help with infra tooling
  .github/actions/should_run_monty/check_changed_files.sh
  .rsyncignore
Labels: infrastructure, triaged
